name: Process Zip Files

on:
  push:
    branches:
      - main

jobs:
  process_files:
    name: Process Zip Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List zip files
        run: |
          # List all .zip files in the specified directory
          ZIP_FILES=$(find path/to/your/directory -type f -name "*.zip")
          echo "Found zip files: $ZIP_FILES"
          echo "::set-output name=zip_files::$ZIP_FILES"

      - name: Process each zip file
        id: process_zip
        run: |
          # Initialize an empty array for storing file information
          FILE_INFO_ARRAY=()

          # Process each zip file
          for ZIP_FILE in ${{ steps.process_files.outputs.zip_files }}; do
            NAME=$(basename "$ZIP_FILE")
            CHECKSUM=$(md5sum "$ZIP_FILE" | awk '{print $1}')
            SIZE=$(stat -c %s "$ZIP_FILE")
